# Generated by Django 5.0.7 on 2024-08-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoAlturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_id', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('carnet_alturas_numero', models.CharField(max_length=50)),
                ('fecha_curso', models.DateField()),
                ('entidad_curso', models.CharField(max_length=100)),
            ],
        ),
    ]
